spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/pay?characterEncoding=UTF-8&useSSL=false
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
  level:
    top.linzeliang.pay: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
wx:
  app-id: xxxx
  mch-id: xxxx
  mch-key: xxxx
  notify-url: http://4khtna.natappfree.cc/pay/notify
  return-url: http://127.0.0.1
alipay:
  app-id: xxxx
  private-key: xxxx
  alipay-public-key: xxxx
  notify-url: http://4khtna.natappfree.cc/pay/notify
  return-url: http://127.0.0.1:8080/tmall/bought
server:
  port: 8081